version: '3.8'

services:
  # Highly Available Zeebe Cluster
  zeebe:
    image: camunda/zeebe:8.4.2
    deploy:
      replicas: 3
    environment:
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=2
      - ZEEBE_BROKER_NETWORK_HOST=0.0.0.0
      - ZEEBE_BROKER_GATEWAY_ENABLE=true
      - ZEEBE_BROKER_GATEWAY_SECURITY_PLAINTEXT=false
      - ZEEBE_BROKER_GATEWAY_SECURITY_CERTIFICATEPATH=/secrets/zeebe.crt
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_JVM_OPTS=-Xms4g -Xmx4g
    volumes:
      - zeebe_data:/usr/local/zeebe/data
      - ./secrets:/secrets:ro
    networks:
      - camunda-net

  # Elasticsearch Cluster
  elasticsearch:
    image: elasticsearch:7.17.10
    deploy:
      replicas: 3
    environment:
      - discovery.type=zen
      - cluster.name=camunda-cluster
      - node.master=true
      - node.data=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - camunda-net

  # Operate with OAuth2
  operate:
    image: camunda/operate:8.4.2
    environment:
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ELASTICSEARCH_USERNAME=elastic
      - CAMUNDA_OPERATE_ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID=operate
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET=${OAUTH_SECRET}
    depends_on:
      - elasticsearch
    networks:
      - camunda-net

  # Spring Boot App (Production Config)
  workflow-app:
    build: .
    environment:
      - ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS=zeebe:26500
      - ZEEBE_CLIENT_SECURITY_CERTIFICATEPATH=/secrets/zeebe.crt
    volumes:
      - ./secrets:/secrets:ro
    networks:
      - camunda-net

volumes:
  zeebe_data:
    driver: cloud-storage-driver
    driver_opts:
      type: gp2
      size: 100Gi
  es_data:
    driver: cloud-storage-driver

networks:
  camunda-net:
    driver: overlay